steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-docker.pkg.dev/searce-playground-v1/ganesh-repo/nodejs-sample:${SHORT_SHA}
      - '-f'
      - source-code/sample-nodejs/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-docker.pkg.dev/searce-playground-v1/ganesh-repo/nodejs-sample:${SHORT_SHA}
timeout: 3600s
images:
  - >-
    asia-docker.pkg.dev/searce-playground-v1/ganesh-repo/nodejs-sample:${SHORT_SHA}
logsBucket: 'gs://ganesh-test-bucket-02'  
options:
  substitutionOption: ALLOW_LOOSE
  logging: GCS_ONLY
