steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/my-app-vue:latest', '.' ]
images:
- 'gcr.io/$PROJECT_ID/my-app-vue:latest'
options:
  logging: CLOUD_LOGGING_ONLY
