apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-app-vue
  name: my-app-vue
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-app-vue
  template:
    metadata:
      labels:
        run: my-app-vue
    spec:
      containers:
      - image: gcr.io/gcb-security-bu/my-app-vue:latest #Replace [PROJECT-ID] accordingly
        name: my-app-vue
        ports:
        - containerPort: 8080
